### ISSUE TITLE
How is it installed?

### ISSUE THREAD

**Issue by Ki11Z0n3** [heloisatech/emulationstationES#2]
Hi, I've been looking for information and I can't find a way to install this, where is the emulationstationES.po file copied?
Thanks

**Comment by heloisatech** [comment]
Hi. The translation has been discontinued.  it's from a very old version. Thanks

**Comment by heloisatech** [comment]
> Hi, I've been looking for information and I can't find a way to install this, where is the emulationstationES.po file copied?
> Thanks

https://github.com/heloisatech/TranslationEmulationStation-TraduzirEmulationStation#readme

**Comment by heloisatech** [comment]
> Hi, I've been looking for information and I can't find a way to install this, where is the emulationstationES.po file copied?
> Thanks

Hi. The translation has been discontinued. it's from a very old version. Thanks
